title: Meu BLog
description: Testes de programação base

url: http://luigimd.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Início
   url: /index.html
 - title: Sobre
   url: /about
 - title: Contato
   url: /contact

social:
   github: luigimd
   twitter: luigimd12345
   facebook: Luigi Dominoni
   email: luigidominoni@hotmail.com

google_analytics: "alguma coisa"
